### ISSUE TITLE
Sign-messge. Specify an id of an input field as message source

### ISSUE THREAD

**Issue by hirishh** [lisk-builders/lisk-buttons#17]
## Proposal of Enhancement 

It would be useful to have an `source-id` parameter on sign-message button, mutually exclusive with `message` parameter. On click the message is taken from the input specified in the `source-id` parameter.

## Example

```
<input id='messageToSign' type='text' />
<lisk-button-sign type="hub" source-id="messageToSign" title="Sign the input field with Lisk!"></lisk-button-sign>
```

**Comment by alepop** [comment]
Another idea is to make sign widget like this:
<img width="411" alt="screen shot 2018-06-15 at 16 39 09" src="https://user-images.githubusercontent.com/922338/41470898-ac7531ba-70ba-11e8-8ba6-6a8082ad42ae.png">
or better to stay with simple buttons?

**Comment by hirishh** [comment]
I like the idea! We can do both, just to add more flexibility to this tool

**Comment by alepop** [comment]
for the record: documentation should be updated with an explanation of new feature

**Comment by hirishh** [comment]
Here we go: https://github.com/lisk-builders/lisk-buttons/pull/19
